_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  WEIGHTS: "model_2.pth"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  SparseRCNN:
    NUM_PROPOSALS: 100
    NUM_CLASSES: 2
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST:  ("coco_2017_val",)
SOLVER:
  STEPS: (21000, 25000)
  MAX_ITER: 54000
  CHECKPOINT_PERIOD: 5000
INPUT:
  CROP:
    ENABLED: False
  FORMAT: "RGB"
